add bios type

diff --git a/vmmaestro b/vmmaestro
--- a/vmmaestro
+++ b/vmmaestro
@@ -171,16 +171,28 @@ function create_mem
 ##############################
 function create_bios
 {
-  if [[ x$bios_menu == 'y' ]]; then
-    bios_args="menu=on"
-  else
-    bios_args=''
-  fi
-  case  "$bios_type" in
-    '0')
+  bios_args=''
+  if [[ x$bios_type != x ]]; then
+    if [[ $bios_type == 'uefi' ]]; then
+      if [[ x$bios_file != x ]]; then
+        if [[ x$bios_nvram != x ]]; then
+          bios_args=$bios_args'-drive if=pflash,format=raw,readonly,file='$bios_file' '
+          bios_args=$bios_args'-drive if=pflash,format=raw,file='$bios_nvram
+        else
+          bios_args='-drive if=pflash,format=raw,file='$bios_file
+        fi
+      else
+        echo "Missing UEFI file."
+        exit 9
+      fi
+    else
       if [[ x$bios_file != x ]]; then
         bios_args=$bios_args'-smbios file='$bios_file
       fi
+    fi
+  fi
+  case  "$bios_type" in
+    '0')
       bios_args=$bios_args' -smbios type=0'
       if [[ x$bios_vendor != x ]]; then
         bios_args=$bios_args',vender='$bios_vendor
@@ -196,9 +208,6 @@ function create_bios
       fi
       ;;
     '1')
-      if [[ x$bios_file != x ]]; then
-        bios_args=$bios_args'-smbios file='$bios_file
-      fi
       bios_args=$bios_args' -smbios type=1'
       if [[ x$bios_manufacturer != x ]]; then
         bios_args=$bios_args',manufacturer='$bios_manufacturer
@@ -222,16 +231,91 @@ function create_bios
         bios_args=$bios_args',family='$bios_family
       fi
       ;;
-    'uefi')
-      if [[ x$bios_file != x ]]; then
-        if [[ x$bios_nvram != x ]]; then
-          bios_args=$bios_args'-drive if=pflash,format=raw,readonly,file='$bios_file' '
-          bios_args=$bios_args'-drive if=pflash,format=raw,file='$bios_nvram
-        else
-          bios_args='-drive if=pflash,format=raw,file='$bios_file
-        fi
-      else
-        bios_args=''
+    '2')
+      bios_args=$bios_args' -smbios type=2'
+      if [[ x$bios_manufacturer != x ]]; then
+        bios_args=$bios_args',manufacturer='$bios_manufacturer
+      fi
+      if [[ x$bios_product != x ]]; then
+        bios_args=$bios_args',product='$bios_product
+      fi
+      if [[ x$bios_version != x ]]; then
+        bios_args=$bios_args',version='$bios_version
+      fi
+      if [[ x$bios_serial != x ]]; then
+        bios_args=$bios_args',serial='$bios_serial
+      fi
+      if [[ x$bios_asset != x ]]; then
+        bios_args=$bios_args',asset='$bios_asset
+      fi
+      if [[ x$bios_location != x ]]; then
+        bios_args=$bios_args',location='$bios_location
+      fi
+      if [[ x$bios_family != x ]]; then
+        bios_args=$bios_args',family='$bios_family
+      fi
+      ;;
+    '3')
+      bios_args=$bios_args' -smbios type=3'
+      if [[ x$bios_manufacturer != x ]]; then
+        bios_args=$bios_args',manufacturer='$bios_manufacturer
+      fi
+      if [[ x$bios_version != x ]]; then
+        bios_args=$bios_args',version='$bios_version
+      fi
+      if [[ x$bios_serial != x ]]; then
+        bios_args=$bios_args',serial='$bios_serial
+      fi
+      if [[ x$bios_asset != x ]]; then
+        bios_args=$bios_args',asset='$bios_asset
+      fi
+      if [[ x$bios_sku != x ]]; then
+        bios_args=$bios_args',sku='$bios_sku
+      fi
+      ;;
+    '4')
+      bios_args=$bios_args' -smbios type=4'
+      if [[ x$bios_sock != x ]]; then
+        bios_args=$bios_args',sock_pfx='$bios_sock
+      fi
+      if [[ x$bios_manufacturer != x ]]; then
+        bios_args=$bios_args',manufacturer='$bios_manufacturer
+      fi
+      if [[ x$bios_version != x ]]; then
+        bios_args=$bios_args',version='$bios_version
+      fi
+      if [[ x$bios_serial != x ]]; then
+        bios_args=$bios_args',serial='$bios_serial
+      fi
+      if [[ x$bios_asset != x ]]; then
+        bios_args=$bios_args',asset='$bios_asset
+      fi
+      if [[ x$bios_part != x ]]; then
+        bios_args=$bios_args',part='$bios_part
+      fi
+      ;;
+    '17')
+      bios_args=$bios_args' -smbios type=17'
+      if [[ x$bios_loc_pfx != x ]]; then
+        bios_args=$bios_args',loc_pfx='$bios_loc_pfx
+      fi
+      if [[ x$bios_bank != x ]]; then
+        bios_args=$bios_args',bank='$bios_bank
+      fi
+      if [[ x$bios_manufacturer != x ]]; then
+        bios_args=$bios_args',manufacturer='$bios_manufacturer
+      fi
+      if [[ x$bios_serial != x ]]; then
+        bios_args=$bios_args',serial='$bios_serial
+      fi
+      if [[ x$bios_asset != x ]]; then
+        bios_args=$bios_args',asset='$bios_asset
+      fi
+      if [[ x$bios_part != x ]]; then
+        bios_args=$bios_args',part='$bios_part
+      fi
+      if [[ x$bios_speed != x ]]; then
+        bios_args=$bios_args',speed='$bios_speed
       fi
       ;;
     '*')
@@ -361,6 +445,13 @@ function create_bootorder
   boot_args=""
   if [[ x$boot_order != x ]]; then
     boot_args='-boot '$boot_order
+    if [[ x$bios_menu == 'y' ]]; then
+      boot_args=$boot_args",menu=on"
+    fi
+  else
+    if [[ x$bios_menu == 'y' ]]; then
+      boot_args="-boot menu=on"
+    fi
   fi
 }
 
